option:
  p: WIP
  x: xxxx
list:
  -chore: add Oyster build script @ this command is ignored @
  -docs: explain hat wobble @ this command will be show in picker @
  -feat: add beta sequence @ but not writen in command line@
  -fix: remove broken @confirmation@ message @ so you can write something @
  -refactor: share logic between 4d3d3d3 and flarhgunnstow
  -style: convert tabs to spaces
  -test: ensure Tayne retains clothing
